[package]
name = "repro"
version = "0.1.0"
authors = ["nobody@example.com"]
edition = "2018"
description = "repro"

[dependencies.sdl2]
version = "0.35.1"
default-features = false
features = []

[profile.release]
lto = true # <-